// priority: 98
StartupEvents.registry("block", event => {
    event.create("barnarda_log", "basic")
        .noValidSpawns(true)
        .hardness(100)
        .soundType("wood")
        .mapColor("wood")
        .tagBlock("mineable/axe")
        .texture("particle", "kubejs:block/barnarda_log_side")
        .texture("up", "kubejs:block/barnarda_log_top")
        .texture("down", "kubejs:block/barnarda_log_top")
        .texture("north", "kubejs:block/barnarda_log_side")
        .texture("south", "kubejs:block/barnarda_log_side")
        .texture("east", "kubejs:block/barnarda_log_side")
        .texture("west", "kubejs:block/barnarda_log_side")
    event.create("barnarda_leaves", "basic")
        .noValidSpawns(true)
        .hardness(100)
        .defaultTranslucent()
        .soundType("azalea_leaves")
        .mapColor("leaves")
        .tagBlock("mineable/hoe")
        .requiresTool(true)
    event.create("barnarda_wood", "basic")
        .noValidSpawns(true)
        .hardness(100)
        .soundType("wood")
        .mapColor("wood")
        .tagBlock("mineable/axe")
        .textureAll("kubejs:block/barnarda_log_side")
    event.create("barnarda_planks", "basic")
        .noValidSpawns(true)
        .soundType("wood")
        .hardness(100)
        .mapColor("wood")
        .tagBlock("mineable/axe")
    event.create("barnarda_stairs", "stairs")
        .noValidSpawns(true)
        .soundType("wood")
        .hardness(100)
        .mapColor("wood")
        .tagBlock("mineable/axe")
    event.create("barnarda_slab", "slab")
        .noValidSpawns(true)
        .soundType("wood")
        .hardness(100)
        .mapColor("wood")
        .tagBlock("mineable/axe")
    event.create("barnarda_fence", "fence")
        .noValidSpawns(true)
        .soundType("wood")
        .hardness(100)
        .mapColor("wood")
        .tagBlock("mineable/axe")
    event.create("barnarda_fence_gate", "fence_gate")
        .noValidSpawns(true)
        .soundType("wood")
        .hardness(100)
        .mapColor("wood")
        .tagBlock("mineable/axe")
    event.create("barnarda_pressure_plate", "pressure_plate")
        .noValidSpawns(true)
        .soundType("wood")
        .hardness(100)
        .mapColor("wood")
        .tagBlock("mineable/axe")
    event.create("barnarda_button", "button")
        .noValidSpawns(true)
        .soundType("wood")
        .hardness(100)
        .mapColor("wood")
        .tagBlock("mineable/axe")
    event.create("variation_wood", "basic")
        .noValidSpawns(true)
        .soundType("wood")
        .mapColor("wood")
        .textureAll("kubejs:block/variation_wood_top")
        .texture("up", "kubejs:block/variation_wood_top")
        .texture("down", "kubejs:block/variation_wood_top")
        .texture("north", "kubejs:block/variation_wood")
        .texture("south", "kubejs:block/variation_wood")
        .texture("east", "kubejs:block/variation_wood")
        .texture("west", "kubejs:block/variation_wood")
    event.create("magic_core", "basic")
        .lightLevel(2)
        .textureAll("gtceu:block/casings/magic/absorber/active/side")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("space_elevator_internal_support", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureAll("gtlcore:block/structure")
        .texture("up", "gtlcore:block/structure")
        .texture("down", "gtlcore:block/structure")
        .texture("north", "gtlcore:block/internal_support")
        .texture("south", "gtlcore:block/internal_support")
        .texture("east", "gtlcore:block/internal_support")
        .texture("west", "gtlcore:block/internal_support")
    event.create("module_base", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureAll("gtlcore:block/structure")
        .texture("up", "gtlcore:block/structure")
        .texture("down", "gtlcore:block/high_strength_concrete")
        .texture("north", "gtlcore:block/high_strength_concrete")
        .texture("south", "gtlcore:block/high_strength_concrete")
        .texture("east", "gtlcore:block/high_strength_concrete")
        .texture("west", "gtlcore:block/high_strength_concrete")
    event.create("molecular_coil", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .textureAll("gtlcore:block/molecular_coil_top")
        .texture("up", "gtlcore:block/molecular_coil_top")
        .texture("down", "gtlcore:block/molecular_coil_top")
        .texture("north", "gtlcore:block/molecular_coil")
        .texture("south", "gtlcore:block/molecular_coil")
        .texture("east", "gtlcore:block/molecular_coil")
        .texture("west", "gtlcore:block/molecular_coil")
    event.create("dyson_receiver_casing", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .textureAll("gtlcore:block/dyson_receiver_casing")
        .texture("up", "gtlcore:block/dyson_receiver_casing")
        .texture("down", "gtlcore:block/dyson_receiver_casing")
        .texture("north", "gtlcore:block/dyson_receiver_casing_side")
        .texture("south", "gtlcore:block/dyson_receiver_casing_side")
        .texture("east", "gtlcore:block/dyson_receiver_casing_side")
        .texture("west", "gtlcore:block/dyson_receiver_casing_side")
    event.create("dyson_deployment_magnet", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .textureAll("gtlcore:block/dyson_deployment_magnet")
        .texture("up", "gtlcore:block/dyson_deployment_magnet")
        .texture("down", "gtlcore:block/dyson_deployment_magnet")
        .texture("north", "gtlcore:block/dyson_deployment_magnet_side")
        .texture("south", "gtlcore:block/dyson_deployment_magnet_side")
        .texture("east", "gtlcore:block/dyson_deployment_magnet_side")
        .texture("west", "gtlcore:block/dyson_deployment_magnet_side")
    event.create("speeding_pipe", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .texture("particle", "gtlcore:block/speeding_pipe_side")
        .texture("up", "gtlcore:block/speeding_pipe_top")
        .texture("down", "gtlcore:block/speeding_pipe_top")
        .texture("north", "gtlcore:block/speeding_pipe_side")
        .texture("south", "gtlcore:block/speeding_pipe_side")
        .texture("east", "gtlcore:block/speeding_pipe_side")
        .texture("west", "gtlcore:block/speeding_pipe_side")
    event.create("red_steel_casing", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .texture("particle", "gtlcore:block/red_steel_casing_side")
        .texture("up", "gtlcore:block/red_steel_casing_top")
        .texture("down", "gtlcore:block/red_steel_casing_top")
        .texture("north", "gtlcore:block/red_steel_casing_side")
        .texture("south", "gtlcore:block/red_steel_casing_side")
        .texture("east", "gtlcore:block/red_steel_casing_side")
        .texture("west", "gtlcore:block/red_steel_casing_side")

    event.create("diamond_compressed_block", "basic")
        .noValidSpawns(true)
        .soundType("stone")
        .mapColor("stone")
        .tagBlock("mineable/pickaxe")
        .textureAll("minecraft:block/diamond_block")

})
StartupEvents.registry("fluid", event => {
    event.create("gelid_cryotheum")
        .flowingTexture("kubejs:block/fluid/gelid_cryotheum_flow")
        .stillTexture("kubejs:block/fluid/gelid_cryotheum")
        .temperature(10)
        .luminosity(8)
        .bucketColor(0x2ab0fa)
})