// priority: 98
StartupEvents.registry("block", event => {
    event.create("barnarda_log", "basic")
        .noValidSpawns(true)
        .hardness(100)
        .soundType("wood")
        .mapColor("wood")
        .tagBlock("mineable/axe")
        .texture("particle", "kubejs:block/barnarda_log_side")
        .texture("up", "kubejs:block/barnarda_log_top")
        .texture("down", "kubejs:block/barnarda_log_top")
        .texture("north", "kubejs:block/barnarda_log_side")
        .texture("south", "kubejs:block/barnarda_log_side")
        .texture("east", "kubejs:block/barnarda_log_side")
        .texture("west", "kubejs:block/barnarda_log_side")
    event.create("barnarda_leaves", "basic")
        .noValidSpawns(true)
        .hardness(100)
        .defaultTranslucent()
        .soundType("azalea_leaves")
        .mapColor("leaves")
        .tagBlock("mineable/hoe")
        .requiresTool(true)
    event.create("barnarda_wood", "basic")
        .noValidSpawns(true)
        .hardness(100)
        .soundType("wood")
        .mapColor("wood")
        .tagBlock("mineable/axe")
        .textureAll("kubejs:block/barnarda_log_side")
    event.create("barnarda_planks", "basic")
        .noValidSpawns(true)
        .soundType("wood")
        .hardness(100)
        .mapColor("wood")
        .tagBlock("mineable/axe")
    event.create("barnarda_stairs", "stairs")
        .noValidSpawns(true)
        .soundType("wood")
        .hardness(100)
        .mapColor("wood")
        .tagBlock("mineable/axe")
    event.create("barnarda_slab", "slab")
        .noValidSpawns(true)
        .soundType("wood")
        .hardness(100)
        .mapColor("wood")
        .tagBlock("mineable/axe")
    event.create("barnarda_fence", "fence")
        .noValidSpawns(true)
        .soundType("wood")
        .hardness(100)
        .mapColor("wood")
        .tagBlock("mineable/axe")
    event.create("barnarda_fence_gate", "fence_gate")
        .noValidSpawns(true)
        .soundType("wood")
        .hardness(100)
        .mapColor("wood")
        .tagBlock("mineable/axe")
    event.create("barnarda_pressure_plate", "pressure_plate")
        .noValidSpawns(true)
        .soundType("wood")
        .hardness(100)
        .mapColor("wood")
        .tagBlock("mineable/axe")
    event.create("barnarda_button", "button")
        .noValidSpawns(true)
        .soundType("wood")
        .hardness(100)
        .mapColor("wood")
        .tagBlock("mineable/axe")
    event.create("variation_wood", "basic")
        .noValidSpawns(true)
        .soundType("wood")
        .mapColor("wood")
        .textureAll("kubejs:block/variation_wood_top")
        .texture("up", "kubejs:block/variation_wood_top")
        .texture("down", "kubejs:block/variation_wood_top")
        .texture("north", "kubejs:block/variation_wood")
        .texture("south", "kubejs:block/variation_wood")
        .texture("east", "kubejs:block/variation_wood")
        .texture("west", "kubejs:block/variation_wood")
    event.create("magic_core", "basic")
        .lightLevel(2)
        .textureAll("gtceu:block/casings/magic/absorber/active/side")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)

    event.create("diamond_compressed_block", "basic")
        .noValidSpawns(true)
        .soundType("stone")
        .mapColor("stone")
        .tagBlock("mineable/pickaxe")
        .textureAll("minecraft:block/diamond_block")

})
StartupEvents.registry("fluid", event => {
    event.create("gelid_cryotheum")
        .flowingTexture("kubejs:block/fluid/gelid_cryotheum_flow")
        .stillTexture("kubejs:block/fluid/gelid_cryotheum")
        .temperature(10)
        .luminosity(8)
        .bucketColor(0x2ab0fa)
})