ServerEvents.recipes(event => {
    event.remove({ id: "sophisticatedbackpacks:backpack" })
    event.remove({ id: "sophisticatedbackpacks:pickup_upgrade" })
    event.remove({ id: "sophisticatedbackpacks:filter_upgrade" })
    event.remove({ id: "sophisticatedbackpacks:advanced_pickup_upgrade" })
    event.remove({ id: "sophisticatedbackpacks:advanced_filter_upgrade" })
    event.remove({ id: "sophisticatedbackpacks:magnet_upgrade" })
    event.remove({ id: "sophisticatedbackpacks:advanced_magnet_upgrade" })
    event.remove({ id: "sophisticatedbackpacks:advanced_magnet_upgrade_from_basic" })
    event.remove({ id: "sophisticatedbackpacks:compacting_upgrade" })
    event.remove({ id: "sophisticatedbackpacks:advanced_compacting_upgrade" })
    event.remove({ id: "sophisticatedbackpacks:void_upgrade" })
    event.remove({ id: "sophisticatedbackpacks:advanced_void_upgrade" })
    event.remove({ id: "sophisticatedbackpacks:pump_upgrade" })
    event.remove({ id: "sophisticatedbackpacks:battery_upgrade" })
    event.remove({ id: "sophisticatedbackpacks:tank_upgrade" })
    event.remove({ id: "sophisticatedbackpacks:refill_upgrade" })
    event.remove({ id: "sophisticatedbackpacks:advanced_refill_upgrade" })
    event.remove({ id: "sophisticatedbackpacks:inception_upgrade" })
    event.remove({ id: "sophisticatedbackpacks:auto_smelting_upgrade" })
    event.remove({ id: "sophisticatedbackpacks:auto_smoking_upgrade" })
    event.remove({ id: "sophisticatedbackpacks:auto_smoking_upgrade_from_auto_smelting_upgrade" })
    event.remove({ id: "sophisticatedbackpacks:auto_blasting_upgrade" })
    event.remove({ id: "sophisticatedbackpacks:auto_blasting_upgrade_from_auto_smelting_upgrade" })
    event.remove({ id: "sophisticatedbackpacks:stack_upgrade_starter_tier" })
    event.remove({ id: "sophisticatedbackpacks:stack_upgrade_tier_1" })
    event.remove({ id: "sophisticatedbackpacks:stack_upgrade_tier_1_from_starter" })
    event.remove({ id: "sophisticatedbackpacks:stack_upgrade_tier_2" })
    event.remove({ id: "sophisticatedbackpacks:stack_upgrade_tier_3" })
    event.remove({ id: "sophisticatedbackpacks:stack_upgrade_tier_4" })

    event.shapeless("sophisticatedbackpacks:pickup_upgrade", ["sophisticatedbackpacks:upgrade_base", "gtceu:lv_item_collector"])
    event.shapeless("sophisticatedbackpacks:filter_upgrade", ["sophisticatedbackpacks:upgrade_base", "gtceu:item_filter"])
    event.shapeless("sophisticatedbackpacks:advanced_pickup_upgrade", ["sophisticatedbackpacks:pickup_upgrade", "gtceu:item_filter"])
    event.shapeless("sophisticatedbackpacks:advanced_filter_upgrade", ["sophisticatedbackpacks:filter_upgrade", "gtceu:item_tag_filter"])
    event.shapeless("sophisticatedbackpacks:magnet_upgrade", ["sophisticatedbackpacks:upgrade_base", "gtceu:lv_item_magnet"])
    event.shapeless("sophisticatedbackpacks:advanced_magnet_upgrade", ["sophisticatedbackpacks:magnet_upgrade", "gtceu:hv_item_magnet"])
    event.shapeless("sophisticatedbackpacks:compacting_upgrade", ["sophisticatedbackpacks:upgrade_base", "gtceu:lv_electric_piston"])
    event.shapeless("sophisticatedbackpacks:advanced_compacting_upgrade", ["sophisticatedbackpacks:compacting_upgrade", "gtceu:mv_electric_piston"])
    event.shapeless("sophisticatedbackpacks:void_upgrade", ["sophisticatedbackpacks:upgrade_base", "gtceu:item_voiding_cover"])
    event.shapeless("sophisticatedbackpacks:advanced_void_upgrade", ["sophisticatedbackpacks:void_upgrade", "gtceu:advanced_item_voiding_cover"])
    event.shapeless("sophisticatedbackpacks:pump_upgrade", ["sophisticatedbackpacks:upgrade_base", "gtceu:lv_electric_pump"])
    event.shapeless("sophisticatedbackpacks:advanced_pump_upgrade", ["sophisticatedbackpacks:pump_upgrade", "gtceu:mv_electric_pump"])
    event.shapeless("sophisticatedbackpacks:tank_upgrade", ["sophisticatedbackpacks:upgrade_base", "gtceu:bronze_drum"])
    event.shapeless("sophisticatedbackpacks:refill_upgrade", ["sophisticatedbackpacks:upgrade_base", "gtceu:lv_robot_arm"])
    event.shapeless("sophisticatedbackpacks:advanced_refill_upgrade", ["sophisticatedbackpacks:refill_upgrade", "gtceu:mv_robot_arm"])
    event.shapeless("sophisticatedbackpacks:auto_smelting_upgrade", ["sophisticatedbackpacks:smelting_upgrade", "gtceu:lv_conveyor_module"])
    event.shapeless("sophisticatedbackpacks:auto_smoking_upgrade", ["sophisticatedbackpacks:smoking_upgrade", "gtceu:lv_conveyor_module"])
    event.shapeless("sophisticatedbackpacks:auto_blasting_upgrade", ["sophisticatedbackpacks:blasting_upgrade", "gtceu:lv_conveyor_module"])
    event.shapeless("sophisticatedbackpacks:stack_upgrade_starter_tier", ["sophisticatedbackpacks:upgrade_base", "gtceu:lv_super_chest"])
    event.shapeless("sophisticatedbackpacks:stack_upgrade_tier_1", ["sophisticatedbackpacks:stack_upgrade_starter_tier", "gtceu:mv_super_chest"])
    event.shapeless("sophisticatedbackpacks:stack_upgrade_tier_2", ["sophisticatedbackpacks:stack_upgrade_tier_1", "gtceu:hv_super_chest"])
    event.shapeless("sophisticatedbackpacks:stack_upgrade_tier_3", ["sophisticatedbackpacks:stack_upgrade_tier_2", "gtceu:ev_super_chest"])
    event.shapeless("sophisticatedbackpacks:stack_upgrade_tier_4", ["sophisticatedbackpacks:stack_upgrade_tier_3", "gtceu:iv_quantum_chest"])

    event.shaped("sophisticatedbackpacks:backpack", [
        "SLS",
        "LBL",
        "FLF"
    ], {
        S: "#forge:screws/wrought_iron",
        L: "minecraft:leather",
        B: "gtceu:wood_crate",
        F: "minecraft:string"
    })
})
