ServerEvents.recipes(event => {
    event.remove({ id: "enderio:copper_alloy_block" })
    event.remove({ id: "enderio:copper_alloy_ingot" })
    event.remove({ id: "enderio:copper_alloy_nugget" })
    event.remove({ id: "enderio:copper_alloy_nugget_to_ingot" })
    event.remove({ id: "enderio:energetic_alloy_block" })
    event.remove({ id: "enderio:energetic_alloy_ingot" })
    event.remove({ id: "enderio:energetic_alloy_nugget" })
    event.remove({ id: "enderio:energetic_alloy_nugget_to_ingot" })
    event.remove({ id: "enderio:vibrant_alloy_block" })
    event.remove({ id: "enderio:vibrant_alloy_ingot" })
    event.remove({ id: "enderio:vibrant_alloy_nugget" })
    event.remove({ id: "enderio:vibrant_alloy_nugget_to_ingot" })
    event.remove({ id: "enderio:redstone_alloy_block" })
    event.remove({ id: "enderio:redstone_alloy_ingot" })
    event.remove({ id: "enderio:redstone_alloy_nugget" })
    event.remove({ id: "enderio:redstone_alloy_nugget_to_ingot" })
    event.remove({ id: "enderio:conductive_alloy_block" })
    event.remove({ id: "enderio:conductive_alloy_ingot" })
    event.remove({ id: "enderio:conductive_alloy_nugget" })
    event.remove({ id: "enderio:conductive_alloy_nugget_to_ingot" })
    event.remove({ id: "enderio:pulsating_alloy_block" })
    event.remove({ id: "enderio:pulsating_alloy_ingot" })
    event.remove({ id: "enderio:pulsating_alloy_nugget" })
    event.remove({ id: "enderio:pulsating_alloy_nugget_to_ingot" })
    event.remove({ id: "enderio:dark_steel_block" })
    event.remove({ id: "enderio:dark_steel_ingot" })
    event.remove({ id: "enderio:dark_steel_nugget" })
    event.remove({ id: "enderio:dark_steel_nugget_to_ingot" })
    event.remove({ id: "enderio:soularium_block" })
    event.remove({ id: "enderio:soularium_ingot" })
    event.remove({ id: "enderio:soularium_nugget" })
    event.remove({ id: "enderio:soularium_nugget_to_ingot" })
    event.remove({ id: "enderio:end_steel_block" })
    event.remove({ id: "enderio:end_steel_ingot" })
    event.remove({ id: "enderio:end_steel_nugget" })
    event.remove({ id: "enderio:end_steel_nugget_to_ingot" })
    event.remove({ id: "enderio:wood_gear_corner" })
    event.remove({ id: "enderio:wood_gear" })

    event.shapeless(Registries.getItemStack("enderio:ender_fluid_conduit", 64), "gtceu:spacetime_nonuple_fluid_pipe")
    event.shapeless("enderio:item_conduit", "gtceu:spacetime_tiny_fluid_pipe")

    const gtr = event.recipes.gtceu

    gtr.forming_press("gtlcore:wood_gear")
        .itemInputs("4x gtceu:wood_plate")
        .notConsumable("gtceu:gear_casting_mold")
        .itemOutputs("enderio:wood_gear")
        .EUt(16)
        .duration(60)
})