// priority: 98
StartupEvents.registry("block", event => {
    const coils = [
        ["abyssalalloy", "12600", "16", "8"],
        ["titansteel", "14400", "32", "8"],
        ["adamantine", "16200", "32", "9"],
        ["naquadriatictaranium", "18900", "64", "9"],
        ["starmetal", "21600", "64", "9"],
        ["infinity", "36000", "128", "9"],
        ["hypogen", "62000", "256", "9"],
        ["eternity", "96000", "512", "9"]
    ]
    coils.forEach((coil) => {
        event.create(coil[0] + "_coil_block", "gtceu:coil")
            .texture("kubejs:block/" + coil[0] + "_coil_block")
            .temperature(coil[1])
            .energyDiscount(8)
            .level(coil[2])
            .tier(coil[3])
            .coilMaterial(() => GTMaterials.get(coil[0]))
            .tagBlock("mineable/pickaxe")
            .tagBlock("forge:mineable/wrench")
            .hardness(5)
            .requiresTool(true)
            .soundType("metal")
            .mapColor("metal")
            .noValidSpawns(true)
    })
    event.create("titanstone", "basic")
        .noValidSpawns(true)
        .soundType("stone")
        .mapColor("stone")
        .tagBlock("mineable/pickaxe")
        .requiresTool(true)
    event.create("plutostone", "basic")
        .noValidSpawns(true)
        .soundType("stone")
        .mapColor("stone")
        .tagBlock("mineable/pickaxe")
        .requiresTool(true)
    event.create("iostone", "basic")
        .noValidSpawns(true)
        .soundType("stone")
        .mapColor("stone")
        .tagBlock("mineable/pickaxe")
        .requiresTool(true)
    event.create("ganymedestone", "basic")
        .noValidSpawns(true)
        .soundType("stone")
        .mapColor("stone")
        .tagBlock("mineable/pickaxe")
        .requiresTool(true)
    event.create("enceladusstone", "basic")
        .noValidSpawns(true)
        .soundType("stone")
        .mapColor("stone")
        .tagBlock("mineable/pickaxe")
        .requiresTool(true)
    event.create("ceresstone", "basic")
        .noValidSpawns(true)
        .soundType("stone")
        .mapColor("stone")
        .tagBlock("mineable/pickaxe")
        .requiresTool(true)
    event.create("titangrunt", "basic")
        .noValidSpawns(true)
        .soundType("sand")
        .mapColor("sand")
        .tagBlock("mineable/shovel")
    event.create("plutogrunt", "basic")
        .noValidSpawns(true)
        .soundType("sand")
        .mapColor("sand")
        .tagBlock("mineable/shovel")
    event.create("ioash", "basic")
        .noValidSpawns(true)
        .soundType("sand")
        .mapColor("sand")
        .tagBlock("mineable/shovel")
    event.create("ganymedegrunt", "basic")
        .noValidSpawns(true)
        .soundType("sand")
        .mapColor("sand")
        .tagBlock("mineable/shovel")
    event.create("ceresgrunt", "basic")
        .noValidSpawns(true)
        .soundType("sand")
        .mapColor("sand")
        .tagBlock("mineable/shovel")
    event.create("antimatter_charge", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("naquadria_charge", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("leptonic_charge", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("quantum_chromodynamic_charge", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("magic_core", "basic")
        .lightLevel(2)
        .textureAll("gtceu:block/casings/magic/absorber/active/side")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("annihilate_core", "basic")
        .lightLevel(4)
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("neutronium_pipe_casing", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("neutronium_gearbox", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("laser_cooling_casing", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("advanced_assembly_line_unit", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("spacetime_compression_field_generator", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("dimensional_bridge_casing", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("uruium_coil_block", "gtceu:coil")
        .texture("kubejs:block/uruium_coil_block")
        .hardness(5)
        .temperature(273)
        .energyDiscount(1)
        .level(1)
        .tier(1)
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .requiresTool(true)
        .soundType("metal")
        .mapColor("metal")
        .noValidSpawns(true)
    event.create("dimensional_stability_casing", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("machine_casing_circuit_assembly_line", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("space_elevator_mechanical_casing", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("high_strength_concrete", "basic")
        .noValidSpawns(true)
        .soundType("stone")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("space_elevator_support", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureAll("kubejs:block/structure")
        .texture("up", "kubejs:block/structure")
        .texture("down", "kubejs:block/structure")
        .texture("north", "kubejs:block/support")
        .texture("south", "kubejs:block/support")
        .texture("east", "kubejs:block/support")
        .texture("west", "kubejs:block/support")
    event.create("space_elevator_internal_support", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureAll("kubejs:block/structure")
        .texture("up", "kubejs:block/structure")
        .texture("down", "kubejs:block/structure")
        .texture("north", "kubejs:block/internal_support")
        .texture("south", "kubejs:block/internal_support")
        .texture("east", "kubejs:block/internal_support")
        .texture("west", "kubejs:block/internal_support")
    event.create("variation_wood", "basic")
        .noValidSpawns(true)
        .soundType("wood")
        .mapColor("wood")
        .textureAll("kubejs:block/variation_wood_top")
        .texture("up", "kubejs:block/variation_wood_top")
        .texture("down", "kubejs:block/variation_wood_top")
        .texture("north", "kubejs:block/variation_wood")
        .texture("south", "kubejs:block/variation_wood")
        .texture("east", "kubejs:block/variation_wood")
        .texture("west", "kubejs:block/variation_wood")
    event.create("essence_block", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("shining_obsidian", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .resistance(100)
        .hardness(80)
        .lightLevel(2)
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("ender_obsidian", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .resistance(100)
        .hardness(80)
        .lightLevel(12)
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("aggregatione_core", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("infused_obsidian", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .resistance(100)
        .hardness(100)
        .lightLevel(12)
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("draconium_block_charged", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .resistance(100)
        .hardness(100)
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("accelerated_pipeline", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("module_base", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureAll("kubejs:block/structure")
        .texture("up", "kubejs:block/structure")
        .texture("down", "kubejs:block/high_strength_concrete")
        .texture("north", "kubejs:block/high_strength_concrete")
        .texture("south", "kubejs:block/high_strength_concrete")
        .texture("east", "kubejs:block/high_strength_concrete")
        .texture("west", "kubejs:block/high_strength_concrete")
    event.create("module_connector", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("manipulator", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("blaze_blast_furnace_casing", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("dimension_connection_casing", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("dimension_creation_casing", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("machine_casing_grinding_head", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("create_aggregatione_core", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("create_casing", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("command_block_broken", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("chain_command_block_broken", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("create_hpca_component", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("force_field_glass", "gtceu:renderer_glass")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .defaultTranslucent()
        .textureOverrideRenderer("minecraft:block/cube_all", { "all": new ResourceLocation("kubejs", "block/force_field_glass") })
    event.create("spacetime_assembly_line_unit", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("spacetime_assembly_line_casing", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("molecular_casing", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("hollow_casing", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("multi_functional_casing", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("molecular_coil", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .textureAll("kubejs:block/molecular_coil_top")
        .texture("up", "kubejs:block/molecular_coil_top")
        .texture("down", "kubejs:block/molecular_coil_top")
        .texture("north", "kubejs:block/molecular_coil")
        .texture("south", "kubejs:block/molecular_coil")
        .texture("east", "kubejs:block/molecular_coil")
        .texture("west", "kubejs:block/molecular_coil")
    event.create("cold_ice_casing", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("containment_field_generator", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("dyson_control_casing", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureAll("kubejs:block/space_elevator_mechanical_casing")
    event.create("dyson_control_toroid", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("dyson_deployment_casing", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("dyson_deployment_core", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("dyson_receiver_casing", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .textureAll("kubejs:block/dyson_receiver_casing")
        .texture("up", "kubejs:block/dyson_receiver_casing")
        .texture("down", "kubejs:block/dyson_receiver_casing")
        .texture("north", "kubejs:block/dyson_receiver_casing_side")
        .texture("south", "kubejs:block/dyson_receiver_casing_side")
        .texture("east", "kubejs:block/dyson_receiver_casing_side")
        .texture("west", "kubejs:block/dyson_receiver_casing_side")
    event.create("dyson_deployment_magnet", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .textureAll("kubejs:block/dyson_deployment_magnet")
        .texture("up", "kubejs:block/dyson_deployment_magnet")
        .texture("down", "kubejs:block/dyson_deployment_magnet")
        .texture("north", "kubejs:block/dyson_deployment_magnet_side")
        .texture("south", "kubejs:block/dyson_deployment_magnet_side")
        .texture("east", "kubejs:block/dyson_deployment_magnet_side")
        .texture("west", "kubejs:block/dyson_deployment_magnet_side")
    event.create("reactor_core", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("steam_assembly_block", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
    event.create("barnarda_log", "basic")
        .noValidSpawns(true)
        .hardness(100)
        .soundType("wood")
        .mapColor("wood")
        .tagBlock("mineable/axe")
        .texture("particle", "kubejs:block/barnarda_log_side")
        .texture("up", "kubejs:block/barnarda_log_top")
        .texture("down", "kubejs:block/barnarda_log_top")
        .texture("north", "kubejs:block/barnarda_log_side")
        .texture("south", "kubejs:block/barnarda_log_side")
        .texture("east", "kubejs:block/barnarda_log_side")
        .texture("west", "kubejs:block/barnarda_log_side")
    event.create("barnarda_leaves", "basic")
        .noValidSpawns(true)
        .hardness(100)
        .defaultTranslucent()
        .soundType("azalea_leaves")
        .mapColor("leaves")
        .tagBlock("mineable/hoe")
        .requiresTool(true)
    event.create("barnarda_wood", "basic")
        .noValidSpawns(true)
        .hardness(100)
        .soundType("wood")
        .mapColor("wood")
        .tagBlock("mineable/axe")
        .textureAll("kubejs:block/barnarda_log_side")
    event.create("barnarda_planks", "basic")
        .noValidSpawns(true)
        .soundType("wood")
        .hardness(100)
        .mapColor("wood")
        .tagBlock("mineable/axe")
    event.create("barnarda_stairs", "stairs")
        .noValidSpawns(true)
        .soundType("wood")
        .hardness(100)
        .mapColor("wood")
        .tagBlock("mineable/axe")
    event.create("barnarda_slab", "slab")
        .noValidSpawns(true)
        .soundType("wood")
        .hardness(100)
        .mapColor("wood")
        .tagBlock("mineable/axe")
    event.create("barnarda_fence", "fence")
        .noValidSpawns(true)
        .soundType("wood")
        .hardness(100)
        .mapColor("wood")
        .tagBlock("mineable/axe")
    event.create("barnarda_fence_gate", "fence_gate")
        .noValidSpawns(true)
        .soundType("wood")
        .hardness(100)
        .mapColor("wood")
        .tagBlock("mineable/axe")
    event.create("barnarda_pressure_plate", "pressure_plate")
        .noValidSpawns(true)
        .soundType("wood")
        .hardness(100)
        .mapColor("wood")
        .tagBlock("mineable/axe")
    event.create("barnarda_button", "button")
        .noValidSpawns(true)
        .soundType("wood")
        .hardness(100)
        .mapColor("wood")
        .tagBlock("mineable/axe")
    event.create("speeding_pipe", "basic")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .texture("particle", "kubejs:block/speeding_pipe_side")
        .texture("up", "kubejs:block/speeding_pipe_top")
        .texture("down", "kubejs:block/speeding_pipe_top")
        .texture("north", "kubejs:block/speeding_pipe_side")
        .texture("south", "kubejs:block/speeding_pipe_side")
        .texture("east", "kubejs:block/speeding_pipe_side")
        .texture("west", "kubejs:block/speeding_pipe_side")

    //ctm
    event.create("dimension_injection_casing", "gtceu:renderer")
        .noValidSpawns(true)
        .soundType("stone")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureOverrideRenderer("minecraft:block/cube_all", { "all": new ResourceLocation("gtceu", "block/casings/hpca/high_power_casing") })

    event.create("dragon_strength_tritanium_casing", "gtceu:renderer")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureOverrideRenderer("minecraft:block/cube_all", { "all": new ResourceLocation("kubejs", "block/extreme_strength_tritanium_casing") })

    event.create("echo_casing", "gtceu:renderer")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureOverrideRenderer("minecraft:block/cube_all", { "all": new ResourceLocation("gtceu", "block/casings/solid/machine_casing_sturdy_hsse") })

    event.create("stellar_containment_casing", "gtceu:renderer")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureOverrideRenderer("minecraft:block/cube_all", { "all": new ResourceLocation("kubejs", "block/stellar_containment_casing") })

    event.create("aluminium_bronze_casing", "gtceu:renderer")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureOverrideRenderer("minecraft:block/cube_all", { "all": new ResourceLocation("kubejs", "block/aluminium_bronze_casing") })

    event.create("antifreeze_heatproof_machine_casing", "gtceu:renderer")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureOverrideRenderer("minecraft:block/cube_all", { "all": new ResourceLocation("kubejs", "block/antifreeze_heatproof_machine_casing") })

    event.create("dimensionally_transcendent_casing", "gtceu:renderer")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureOverrideRenderer("minecraft:block/cube_all", { "all": new ResourceLocation("kubejs", "block/dimensionally_transcendent_casing") })

    event.create("enhance_hyper_mechanical_casing", "gtceu:renderer")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureOverrideRenderer("minecraft:block/cube_all", { "all": new ResourceLocation("kubejs", "block/enhance_hyper_mechanical_casing") })

    event.create("extreme_strength_tritanium_casing", "gtceu:renderer")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureOverrideRenderer("minecraft:block/cube_all", { "all": new ResourceLocation("kubejs", "block/extreme_strength_tritanium_casing") })

    event.create("graviton_field_constraint_casing", "gtceu:renderer")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureOverrideRenderer("minecraft:block/cube_all", { "all": new ResourceLocation("kubejs", "block/graviton_field_constraint_casing") })

    event.create("hyper_mechanical_casing", "gtceu:renderer")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureOverrideRenderer("minecraft:block/cube_all", { "all": new ResourceLocation("kubejs", "block/hyper_mechanical_casing") })

    event.create("infinity_glass", "gtceu:renderer_glass")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .defaultTranslucent()
        .textureOverrideRenderer("minecraft:block/cube_all", { "all": new ResourceLocation("kubejs", "block/infinity_glass") })

    event.create("iridium_casing", "gtceu:renderer")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureOverrideRenderer("minecraft:block/cube_all", { "all": new ResourceLocation("kubejs", "block/iridium_casing") })

    event.create("lafium_mechanical_casing", "gtceu:renderer")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureOverrideRenderer("minecraft:block/cube_all", { "all": new ResourceLocation("kubejs", "block/lafium_mechanical_casing") })

    event.create("oxidation_resistant_hastelloy_n_mechanical_casing", "gtceu:renderer")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureOverrideRenderer("minecraft:block/cube_all", { "all": new ResourceLocation("kubejs", "block/oxidation_resistant_hastelloy_n_mechanical_casing") })

    event.create("pikyonium_machine_casing", "gtceu:renderer")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureOverrideRenderer("minecraft:block/cube_all", { "all": new ResourceLocation("kubejs", "block/pikyonium_machine_casing") })

    event.create("sps_casing", "gtceu:renderer")
        .noValidSpawns(true)
        .soundType("stone")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureOverrideRenderer("minecraft:block/cube_all", { "all": new ResourceLocation("kubejs", "block/sps_casing") })

    event.create("naquadah_alloy_casing", "gtceu:renderer")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureOverrideRenderer("minecraft:block/cube_all", { "all": new ResourceLocation("kubejs", "block/hyper_mechanical_casing") })

    event.create("process_machine_casing", "gtceu:renderer")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureOverrideRenderer("minecraft:block/cube_all", { "all": new ResourceLocation("gtceu", "block/casings/solid/machine_casing_solid_steel") })

        event.create("fission_reactor_casing", "gtceu:renderer")
        .noValidSpawns(true)
        .soundType("metal")
        .mapColor("metal")
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .requiresTool(true)
        .textureOverrideRenderer("minecraft:block/cube_all", { "all": new ResourceLocation("kubejs", "block/fission_reactor_casing") })
})
StartupEvents.registry("fluid", event => {
    event.create("gelid_cryotheum")
        .flowingTexture("kubejs:block/fluid/gelid_cryotheum_flow")
        .stillTexture("kubejs:block/fluid/gelid_cryotheum")
        .temperature(10)
        .luminosity(8)
        .bucketColor(0x2ab0fa)
})