
#设置
[Settings]
	#最低选区高度，可以防止破坏基岩
	#Range: > -1000
	lowHeight = -60
	#undo和redo撤销的最大次数
	#Range: 0 ~ 10000
	undoLimit = 15
	#世界黑名单，格式为"世界名/维度名"，世界名是创建世界时候的名字
	#"主世界/minecraft:overworld"，"下界/minecraft:the_nether"，"末地/minecraft:the_end"
	blackListWorld = ["新的世界/minecraft:the_nether"]
	#使用本MOD的‘建筑耗材’方块代替的方块列表，比如空气、水等不能获取的方块可以填入，会扣除对应数量的‘建筑耗材’方块
	#如果白名单中也有这个方块则会按比例扣除‘建筑耗材’方块， 否则比例为1：1，推荐只填入不能获取的方块
	#会先检查黑名单
	replaceBlockList = ["minecraft:water"]

#普通玩家
[Default]
	#普通玩家默认选区大小
	#Range: > 0
	defaultValue = 1000
	#
	#放置的时候是否扣除背包方块
	checkInventory = true
	#
	#白名单方块,此名单中的方块按比例扣除，#前面的数字为扣除比例，#号只做分隔使用，没有实际意义，后面的*为匹配这个MOD的所有方块
	#格式为 "比例值#方块名称"
	# 0#ID：则此方块不计算背包数量，无限制放置
	# 1#：则比例为1：1，放置1个方块需要扣除背包中1个
	# 50#：则比例为50：1，放置50个方块需要扣除背包中1个
	# 10#minecraft:* 则所有minecraft方块比例都为10：1，所有minecraft方块放置10个需要扣除背包中1个
	whiteListBlock = ["10#minecraft:oak_log", "5#minecraft:stone"]
	#
	#黑名单方块，优先级：黑名单 > 白名单比例值 > *
	#优先级比白名单高,此名单中的方块均不允许放置，只填入名字即可，不需要前面的#
	blackListBlock = ["minecraft:water", "minecraft:tnt", "akatzumaworldedit:building_consumable"]
	#
	#黑名单标签，此标签中的方块均不允许放置（默认添加了矿物、箱子、潜影盒的标签）
	#可以安装CraftTweaker使用指令/ct hand来查看手中方块的标签
	#只需要填入最后一个:前后的值即可，不需要填入前缀tag:blocks
	blackListTags = ["forge:ores", "forge:storage_blocks", "forge:chests", "minecraft:shulker_boxes", "forge:barrels", "minecraft:guarded_by_piglins"]

#高级玩家
[VipSettings]
	#高级玩家名单
	vipPlayerList = ["高级玩家名单"]
	#
	#高级玩家选区大小
	#Range: > 0
	vipValue = 100000
	#
	#高级玩家放置的时候是否扣除背包方块
	VipCheckInventory = true
	#
	#白名单方块,此名单中的方块按比例扣除，#前面的数字为扣除比例，#号只做分隔使用，没有实际意义，后面的*为匹配这个MOD的所有方块
	#格式为 "比例值#方块名称"
	# 0#：则此方块不计算背包数量，无限制放置
	# 1#：则比例为1：1，放置1个方块需要扣除背包中1个
	# 50#：则比例为50：1，放置50个方块需要扣除背包中1个
	# 10#minecraft:* 则所有minecraft方块比例都为10：1，所有minecraft方块放置10个需要扣除背包中1个
	VipWhiteListBlock = ["0#minecraft:oak_log", "10#minecraft:stone"]
	#
	#黑名单方块，优先级：黑名单 > 白名单比例值 > *
	#优先级比白名单高,此名单中的方块均不允许放置，只填入名字即可，不需要前面的#
	VipBlackListBlock = ["minecraft:water"]
	#
	#黑名单标签，此标签中的方块均不允许放置（默认添加了矿物、箱子、潜影盒的标签）
	#可以安装CraftTweaker使用指令/ct hand来查看手中方块的标签
	#只需要填入最后一个:前后的值即可，不需要填入前缀tag:blocks
	blackListTags = ["forge:ores", "forge:storage_blocks", "forge:chests", "minecraft:shulker_boxes", "forge:barrels", "minecraft:guarded_by_piglins"]

